[Issue #158] remove dead code
mozilla-sensorweb/sensorthings pull request #210
Opened 2017-01-06 23:14 UTC by russnicoletti

2017-01-09 15:52 UTC, ferjm requested changes
Thank you Russ. Did you check Alberto's comment at https://github.com/mozilla-sensorweb/sensorthings/issues/158#issuecomment-271260459 ? I think he is right about it.

2017-01-31 23:42 UTC, russnicoletti commented
I verified Alberto is correct (https://github.com/mozilla-sensorweb/sensorthings/issues/158#issuecomment-276529755). I have updated this PR to remove L80-82 and to restore L98-L112.

2017-01-31 23:44 UTC, russnicoletti commented
Code coverage before the change:
`associations.js         |    84.21 |    63.64 |       75 |    84.21 |... 112,128,133 |`

Code coverate after the change:
 `associations.js         |    87.27 |    70.97 |       75 |    87.27 |... 108,124,129 |`

2017-02-01 13:03 UTC, ferjm approved these changes

2017-02-01 13:04 UTC, merged